[project]
name = "claude-evaluator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chaewonkong", email = "chaewonkong@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "claude-agent-sdk>=0.2.157",
    "fastapi[standard]>=0.141.1",
    "typesafe-sdk>=0.7.1",
]

[project.scripts]
claude-evaluator = "claude_evaluator:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "claude_evaluator.main:app"

[tool.ruff.lint]
extend-select = ["I"]
